version: 2.1

executors:
  node:
    docker:
      - image: node:12
        user: node
  gcloud:
    docker:
      - image: google/cloud-sdk:alpine

jobs:
  find-build:
    executor: node
    steps:
      - checkout
      - run:
          name: Find build artifact
          command: |
            npm install
            node src/find-build.js > artifact-url
      - persist_to_workspace:
          root: .
          paths:
            - artifact-url
  deploy:
    executor: gcloud
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Deploy
          command: |
            set -o nounset
            curl -s -f $(< /tmp/workspace/artifact-url) | tar -xz
            cp config/prod.json build/config.json
            echo "$GCP_SA_KEY" > /tmp/sa-key.json
            gcloud auth activate-service-account --key-file=/tmp/sa-key.json
            gcloud app deploy --project=bvdp-saturn-prod --promote --quiet
  delete-old-versions:
    executor: gcloud
    steps:
      - run:
          name: Delete old versions
          command: |
            set -o nounset
            echo "$GCP_SA_KEY" > /tmp/sa-key.json
            gcloud auth activate-service-account --key-file=/tmp/sa-key.json
            gcloud config set project bvdp-saturn-prod
            OLD_VERSIONS=$(gcloud app versions list --service=default --sort-by='~id' --format='value(id)' | sed '1,10d')
            if [ -n "$OLD_VERSIONS" ]; then
              gcloud app versions delete $OLD_VERSIONS --service=default --quiet
            fi

workflows:
  version: 2
  deploy-prod:
    triggers:
      - schedule:
          cron: "0 15 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - find-build
      - deploy:
          requires:
            - find-build
  cleanup:
    triggers:
      - schedule:
          cron: "0 16 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - delete-old-versions
