version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  node:
    docker:
      - image: node:14
        user: node
  gcloud:
    docker:
      - image: google/cloud-sdk:alpine

jobs:
  find-build:
    executor: node
    steps:
      - checkout
      - run:
          name: Find build artifact
          command: "yarn find-build > artifact-url"
      - persist_to_workspace:
          root: .
          paths: [ artifact-url ]
  deploy:
    executor: gcloud
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Deploy
          command: |

            CURRYEAR="$(date +%Y)"
            CURRDATE="$(date +%m/%d/%Y)"

            # Holiday dates specific to 2021 that will need to be updated next year
            HOLIDAYS=("03/12/2021" "03/19/2021" "04/19/2021" "05/28/2021" "05/31/2021" "07/02/2021" "07/05/2021"
            "09/06/2021" "10/11/2021" "11/11/2021" "11/25/2021" "11/26/2021" "12/23/2021")

            # List of Holidays the Broad is closed for every year
            HOLIDAYSEACHYEAR=("01/01" "12/24" "12/25" "12/26" "12/27" "12/28" "12/29" "12/30" "12/31")

            for val in "${HOLIDAYSEACHYEAR[@]}"; do
               HOLIDAYS+=("${val}/${CURRYEAR}")
            done

            # Do not release on Broad Holidays
            for val in "${HOLIDAYS[@]}"; do
                 if [ "${val}" = "${CURRDATE}" ]; then
                    echo Holiday - no release
                    circleci-agent step halt
                    exit 0
                 fi
            done

            if [[ "$PREVENT_DEPLOY" = true ]]; then
              echo PREVENT_DEPLOY is enabled - no release
              circleci-agent step halt
            else
              set -o nounset
              curl -L -s -f $(< /tmp/workspace/artifact-url) | tar -xz
              cp config/prod.json build/config.json
              echo "$GCP_SA_KEY" > /tmp/sa-key.json
              gcloud auth activate-service-account --key-file=/tmp/sa-key.json
              gcloud app deploy --project=bvdp-saturn-prod --promote --quiet
            fi
      - slack/status:
          channel: "C6DTFUCDD" # workbench-release
          include_job_number_field: false
          include_project_field: false
          failure_message: ":sadpanda: $CIRCLE_JOB failed."
          success_message: ":circleci-pass: $CIRCLE_JOB ran successfully."
  delete-old-versions:
    executor: gcloud
    steps:
      - run:
          name: Delete old versions
          command: |
            set -o nounset
            echo "$GCP_SA_KEY" > /tmp/sa-key.json
            gcloud auth activate-service-account --key-file=/tmp/sa-key.json
            gcloud config set project bvdp-saturn-prod
            OLD_VERSIONS=$(gcloud app versions list --service=default --sort-by='~id' --format='value(id)' | sed '1,10d')
            if [ -n "$OLD_VERSIONS" ]; then
              gcloud app versions delete $OLD_VERSIONS --service=default --quiet
            fi

workflows:
  version: 2
  deploy-prod:
    triggers:
      - schedule:
          cron: "0 16 * * 1-5"
          filters:
            branches:
              only:
                - dev
    jobs:
      - find-build
      - deploy:
          requires:
            - find-build
  cleanup:
    triggers:
      - schedule:
          cron: "0 16 * * 1"
          filters:
            branches:
              only:
                - dev
    jobs:
      - delete-old-versions
